### ISSUE TITLE
byob.py - RuntimeError 

### ISSUE THREAD

**Issue by MKCarter** [Dunni3/keypoint-diffusion#11]
Hi,

I am trying to run a protein ligand example using the `byop.py` script:

`python byop.py receptor.pdb reference_ligand.sdf --model_dir=trained_models/gvp_40kp`

However, when running this I get a strange `torch.tensor` error - the full output is shown below:

```
device=device(type='cuda')
/home/michaelcarter/DD_tools/keypoint-diffusion/byop.py:117: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  lig_coords = torch.tensor(lig_coords, dtype=torch.float32)
Traceback (most recent call last):
  File "/home/michaelcarter/DD_tools/keypoint-diffusion/byop.py", line 410, in <module>
    main()
  File "/home/michaelcarter/DD_tools/keypoint-diffusion/byop.py", line 299, in main
    ref_graph = model.encode_receptors(ref_graph)
  File "/home/michaelcarter/DD_tools/keypoint-diffusion/models/ligand_diffuser.py", line 265, in encode_receptors
    g = self.rec_encoder(g, batch_idxs)
  File "/home/michaelcarter/miniconda3/envs/kpdiff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/michaelcarter/miniconda3/envs/kpdiff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/michaelcarter/DD_tools/keypoint-diffusion/models/receptor_encoder_gvp.py", line 221, in forward
    rec_scalar_feat = self.scalar_embed(rec_scalar_feat)
  File "/home/michaelcarter/miniconda3/envs/kpdiff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/michaelcarter/miniconda3/envs/kpdiff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/michaelcarter/miniconda3/envs/kpdiff/lib/python3.10/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/home/michaelcarter/miniconda3/envs/kpdiff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/michaelcarter/miniconda3/envs/kpdiff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/michaelcarter/miniconda3/envs/kpdiff/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 must have the same dtype, but got Bool and Float
```

Any idea why this is happening? 

Many thanks :)

**Comment by Dunni3** [comment]
This should be resolved now. Thanks for raising the issue.
